unstable_features = true
# blank_lines_lower_bound = 1
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
edition = "2021"
enum_discrim_align_threshold = 30
fn_single_line = true
force_multiline_blocks = true
format_strings = true
imports_layout = "HorizontalVertical"
space_before_colon = true
struct_field_align_threshold = 30
where_single_line = true
